### ISSUE TITLE
Questions about First in Line / Up Next

### ISSUE THREAD

**Issue by clyhomna** [Ephellon/Twitch-Tools#1]
When someone starts a stream it doesnt automatically start watching it, 
and how does it decide who it wants to watch?
U should add like some text box to paste channel links of whom I wanna watch..?

**Comment by clyhomna** [comment]
Update: was just blind.
Also its really hard to find the basic "up next" button and im not sure how it works, they are not streaming and it takes me to their stream.

**Comment by Ephellon** [comment]
> When someone starts a stream it doesn't automatically start watching it

- **First in Line/Up Next** adds a queuing service that automatically watches for notifications and new channels. It will go to the stream after `x` minutes (can be changed in your settings)

> How does it decide who it wants to watch?

- **First in Line/Up Next** goes in the order it receives notifications
- The channels under **Up Next** can be drag-n-dropped into new positions

> [You] should add some text box to paste channel links I [want to] watch

- Channels can be drag-n-dropped to the blue **Up Next** area

----

> Its really hard to find the [Up Next] button

- I will look into adding accessibility options
- The **Up Next** button will always be located next to the left of the *Prime Loot* button

> [I'm] not sure how it works&mdash;they are not streaming and it takes me to their stream

- I recommend setting the **First in Line** timer to something that suits your needs &rarr;
    - If the timer is set to a very large number (e.g. `100` minutes), the 5th channel in line will be seen after `500` minutes

**Comment by Mishasama** [comment]
> * I recommend setting the **First in Line** timer to something that suits your needs

I don't even know why you call this feature "first in line". It doesn't even open the live page as soon as it receives a notification that it's on, and it even has a 5-minute minimum. So where is it "first"? And [what is it used for](https://github.com/Ephellon/Twitch-Tools/wiki/First-in-Line---Up-Next)?
