### ISSUE TITLE
Uncaught Error 

### ISSUE THREAD

**Issue by f0rmatme** [Ephellon/Twitch-Tools#10]
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
>     at loadImageData (resemble.js:340:41)
>     at compare (resemble.js:831:13)
>     at wrapper (resemble.js:959:25)
>     at Object.onComplete (resemble.js:962:21)
>     at WAIT_FOR_PAGE (tools.js:13100:34)
> tools.js:2981 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'innerHTML')
>     at AddCustomCSSBlock (tools.js:2981:32)
>     at Initialize (tools.js:12592:9)
>     at async tools.js:12868:17

**Comment by f0rmatme** [comment]
I belive this has caused my webpage to crash once or twice

**Comment by Ephellon** [comment]
Hi. Could you add more information about the issues? Extension version, what was happening beforehand, etc?
