### ISSUE TITLE
Suggestion: Pick which streamer(s) to go to when the current one ends

### ISSUE THREAD

**Issue by VatriXxX** [Ephellon/Twitch-Tools#12]
Hello,
how can i setup to switch automatically if my favorite streamer is going online?
If I drag it into next, that will be automatically switch after 1sec to the offline stream.
I will only switch to the stream if he/she's online.

And after that I would be setup after he/she's offline switch to a specified person.
For example I look Streamer X and if he's going offline it should be automatically switch to Streamer Y that I drag it into a list.

I don't understand the "Up Next" and "Live Reminders" List.

Best regards

**Comment by Ephellon** [comment]
Hello, under `First in Line / Up Next` &rArr; `Options`, ensure the one you pick is set to at least `5 min`

If you already have this done, try disabling `Extras` &rArr; `One Instance`

I am having issues with `One Instance` flipping screens around; currently working on it

**Comment by Ephellon** [comment]
If needed, please refer to #1

**Comment by VatriXxX** [comment]
> Hello, under `First in Line / Up Next` ⇒ `Options`, ensure the one you pick is set to at least `5 min`
> 
> If you already have this done, try disabling `First in Line / Up Next` ⇒ `Extras` ⇒ `One Instance`
> 
> I am having issues with `One Instance` flipping screens around; currently working on it

But with one of `First in Line / Up Next` ⇒ `Options` ? I would set someone of a list? For example if Streamer X online or Streamer Y online.

I have more than one tabs open of twitch.

**Comment by Ephellon** [comment]
Is the `Stay Live` option enabled?

**Comment by Ephellon** [comment]
There's a search bar at the bottom right of the Settings page

**Comment by Ephellon** [comment]
And any of the options other than `Disable`; `Automatic` may work for you

**Comment by VatriXxX** [comment]
Doesn't work, they automatically switch after X minutes to the other stream. But I would have, that the streamer x is going offline than go the streamer y.

**Comment by Ephellon** [comment]
I'm not sure what you're trying to accomplish

**Comment by VatriXxX** [comment]
I would setup a automatically switch function, if streamer x is offline, so open streamer y. But only if he/she's offline.
And not a random streamer.

**Comment by Ephellon** [comment]
That's not an option. You could change the settings to someone who is popular, not popular, you have the most/least point son, etc.

**Comment by VatriXxX** [comment]
Yeah i saw the popular etc. settings.
But thanks for your help.
Is it possible to add this as a feature?

**Comment by Ephellon** [comment]
Add a sub-button option (similar to `R`) during live previews?

**Comment by dskw1** [comment]
Ooh let me tryDevan Grey ***@***.*** (m)On Aug 22, 2024, at 07:14, Ephellon ***@***.***> wrote:﻿
Add a sub-button option (similar to R) during live previews?

**Comment by Ephellon** [comment]
I've already assigned myself

**Comment by dskw1** [comment]
I can try tho.. stillDevan Grey ***@***.*** (m)On Aug 22, 2024, at 09:25, Ephellon ***@***.***> wrote:﻿
I've already assigned myself

**Comment by Ephellon** [comment]
Your email reply is sending all of the footer

**Comment by Ephellon** [comment]
And I already have a solution in mind: *Bunker* — if the queue is empty and the current stream goes offline, head to the person in the *Bunker* and remove them if they're offline
