### ISSUE TITLE
Issue: Context Menu

### ISSUE THREAD

**Issue by 45thhokage** [Ephellon/Twitch-Tools#15]
How do i remove the context menu

**Comment by Ephellon** [comment]
Hi, you can't disable the context menu on *main* content (video, about me, and panels)

**Comment by 45thhokage** [comment]
Any chances of getting that option? I like opening up a bunch of streams first before picking on to settle at and since we don't have "open link in background" it just ends being annoying being forced to go to each and every stream then come back to browser or following. Honestly, might even explain why i watch twitch less lol

**Comment by Ephellon** [comment]
I'm not entirely sure what you're asking but, there are "open link in background" options:

1. `Ctrl` (`Cmd` on Mac) + Click → Open link in new tab
2. `Shift` + Click → Open link in new window
3. `Alt` (`Opt` on Mac) + Click → Download the link (no prompt)

**Comment by 45thhokage** [comment]
that solved my problem
