### ISSUE TITLE
claim drops?

### ISSUE THREAD

**Issue by d0x360** [Ephellon/Twitch-Tools#16]
I see that it claims points and amazon gifts but does it claim drops so the timer begins if there are multiple?

Thanks

**Comment by d0x360** [comment]
actually it's not claiming anything at all now that I've been testing for a
couple hours no chat points, no Amazon stuff etc

**Comment by Ephellon** [comment]
Twitch has had issues for a few months now; it's Twitch, not the extension

**Comment by d0x360** [comment]
is it something that can be fixed?  I don't remember which extension it was
cause I tried a few and one said deprecated.  if that's this one and I have
the time I wouldn't mind taking a crack at it for you...

I couldn't get it to do anything except reload the page constantly if the
chat recovery function was enabled but chat was working fine.

**Comment by Ephellon** [comment]
Added in [`v5.32.14`](https://github.com/Ephellon/Twitch-Tools/releases/tag/5.32.14)
