### ISSUE TITLE
Suggestion: Add hover previews to the main Twitch page

### ISSUE THREAD

**Issue by Luke0094** [Ephellon/Twitch-Tools#19]
**Describe the bug**
As title say preview doesn't work in the front page even if the option is enabled.

**Extension Information**
 - Version: `5.32.11`
 - Source: `Chrome web store`
 - Browser: `chrome (Brave)`
 - Operating System: `Windows`

**Comment by Ephellon** [comment]
I'm assuming you mean the Live Preview when hovering over channels?

**Comment by Ephellon** [comment]
Skimmed thru latest update... nothing interacts with Live Preview. I'll need to install Brave and see what's wrong I guess. Will die that when I get situated

**Comment by Ephellon** [comment]
Previews work just fine for me. It does take a while for the video to play but, it plays after 5s or so...

![image](https://github.com/Ephellon/Twitch-Tools/assets/8632548/3d9fdaf7-ee7a-4498-b8bc-de5ec11b6c28)

**Comment by luchettodj94** [comment]
> Previews work just fine for me. It does take a while for the video to play but, it plays after 5s or so...
> 
> ![image](https://user-images.githubusercontent.com/8632548/273469659-3d9fdaf7-ee7a-4498-b8bc-de5ec11b6c28.png)

Actually I didn't didn't check on "your follow" or "recommended" but in the home page and it should work something like this, no?
<img width="1850" alt="Senza titolo" src="https://github.com/Ephellon/Twitch-Tools/assets/57552558/10d4bdfb-e591-457b-b582-11f1a2bc4f6a">

**Comment by Ephellon** [comment]
Live Previews do not work on the home page

**Comment by luchettodj94** [comment]
> Live Previews do not work on the home page

Then I apologize I got the extension wrong :P It may however be a good suggestion for you (both reccomended and home page one)
