### ISSUE TITLE
Issue: [Volume Change Bug]

### ISSUE THREAD

**Issue by aitronssesin** [Ephellon/Twitch-Tools#2]
When the TTV Tools is activated the volume is bug I want to change the volume but It always change to 100

**Comment by aitronssesin** [comment]
https://user-images.githubusercontent.com/74368135/135152932-b56382ce-2c43-468a-9060-76fa79a65bf4.mp4

**Comment by Ephellon** [comment]
I'll look into it

**Comment by aitronssesin** [comment]
I know what's the problem is the preview stream audio option

**Comment by Ephellon** [comment]
Found the culprit: [`ttv-tools/tools.js:5794`](https://github.com/Ephellon/Twitch-Tools/blob/1e46d134bb37888aa1d47041af8da296cf4f7877/ttv-tools/tools.js#L5974)
