### ISSUE TITLE
Issue: "invalid client" when asking API

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#21]
**Describe the bug**
It open a [page](https://id.twitch.tv/oauth2/authorize?response_type=code&client_id=null&redirect_uri=https%3A%2F%2Fephellon.github.io%2F&response_type=token&scope=user%3Aread%3Afollows%2Buser%3Aread%3Asubscriptions%2Bchat%3Aread&state=d0cf0c25-1bfb-4b3f-ae21-1b787901d8e2), then shows`{"status":400,"message":"invalid client"}`.

**To Reproduce**

It popup a `<div>` to ask me let it use the API. Then I click it.

**Expected behavior**

I don't know

**Screenshots**

![image](https://github.com/user-attachments/assets/6f68c304-e15a-4b21-9594-e69701d95f6e)

**Extension Information**
 - Version: `5.33.4.1`
 - Source: `store`
 - Browser: `edge`
 - Operating System: `Windows` 

**Additional comments**

What it use for?

**Comment by Ephellon** [comment]
The `client_id` parameter is set to `null`, will update the logic that controls that. And it's used to perform some backend searches on Twitch

**Comment by Mishasama** [comment]
[Again](https://id.twitch.tv/oauth2/authorize?response_type=code&client_id=null&redirect_uri=https%3A%2F%2Fephellon.github.io%2FTTVAuth&response_type=token&scope=user%3Aread%3Afollows%20user%3Aread%3Asubscriptions%20chat%3Aread&state=dde36e74-16f5-473c-8405-f4b66c8ac3a9) on 5.34.1

@Ephellon

**Comment by Ephellon** [comment]
Yes, Twitch APIs are currently doing their rounds of going down and coming back up every few hours

- Top stream → API down, points **are not** automatically collected
- Bottom stream → API up, points **are** automatically collected

<img width="888" height="1351" alt="Image" src="https://github.com/user-attachments/assets/6183585c-3283-4fe8-ad65-1cfcc7926ba9" />

**Comment by Mishasama** [comment]
Could this issue be caused by abnormal data volume in our extension request?
