### ISSUE TITLE
Issue: Endless loops of reopen tabs.

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#22]
**Describe the bug**
If you open multiple stream pages, you may encounter a problem where tabs continuously close and reopen.
After a while, a tab might close entirely and refuse to reopen. 

**To Reproduce**

I'm not sure.
1. Open 3 different stream pages (1 is off live, 2 is live)
2. Open another tab and make sure the 3 stream pages are in the background state
3. After a period, when the streams have lag issues, or any tab goes into sleep mode, it starts a dead loop of reloading and reopening the tabs
4. After closing sometimes, some tabs may not open anymore.

**Expected behavior**

Don't mess up the tabs, just refresh it if you can't recover the streams.
And don't refresh the whole page if you can press the red reload player button to fix it. (The [Previews](https://previews-app.com/) is doing good at this.)
You can always reload the inframe (like chats), it doesn't need to refresh the page or even reopen the tab.

**Screenshots**

![image](https://github.com/user-attachments/assets/2c6a06e9-3aa2-41d4-a246-53a24adcf9f5)

**Extension Information**
 - Version: `5.33.4.2`
 - Source: `store`
 - Browser: `edge`
 - Operating System: `Windows` 

**Additional comments**

If you close the tab, it will reset the mute state (`ctrl + m`) and leave the tab group. It's not reasonable to close the tab but not just refresh it. Because it will force you to take the tab to the foreground and interrupt the user's work.

One more question, I've turned off all the options stating that it will reload the page, but it still keeps reopening new tabs, that's a bug too, right?

Upload ID: `bODfxm`

**Comment by Mishasama** [comment]
It looks like can't run at offline stream page.

**Comment by Ephellon** [comment]
Hi @Mishasama, I added some suggestions to the next update `v5.44.4.4`

- Reloaded tabs will now remain in their group (if set)
- Reloaded tabs will **not** automatically refocus (they'll do their reloading in the background)
- Reloaded tabs will stay at their current position (i.e. "3rd from left")
