### ISSUE TITLE
Issue: "Buy when available" doesn't perform purchases

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#23]
**Describe the bug**

After refreshing the page, or move to the next stream. Even if the item can be bought, it still does nothing.

**To Reproduce**

1. Click 'Buy when available'
2. Refresh the page, or start another stream
3. Wait until the item can be bought

**Expected behavior**

Buy when available, no matter when.

**Screenshots**

![image](https://github.com/user-attachments/assets/196cc4d9-097f-47fb-be59-2ce36c79a5ff)

**Extension Information**
 - Version: `5.33.4.3`
 - Source: `store`
 - Browser: `chrome`
 - Operating System: `Windows`

**Additional comments**

**Comment by Ephellon** [comment]
Does the **Twitch Integrity Failure** message pop-up? I fso, it's a known Twitch issue

**Comment by Mishasama** [comment]
I didn't see any popup, it just does nothing.

**Comment by Ephellon** [comment]
I'll have to wait for Twitch's crappy bot-detection to realize I'm human (Twitch Integrity Fail) then I can take a look at this

**Comment by Ephellon** [comment]
_Note: shop IDs are different when the TIF is active_

**Comment by Ephellon** [comment]
I am no longer a bot! Found issue at `tools.js:6560` → `AutoClaimAnswers[sole][id]` should be `AutoClaimAnswers[sole]?.[id] ?? ''`

- `?.` — if the object is not found, default to `null`
- `??` — if the object is not found, use the value to the right

**Comment by Ephellon** [comment]
Will continue testing to make sure it purchases
