### ISSUE TITLE
Issue: Bug in v5.33.4.6 about reload tabs.

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#24]
> I added some suggestions to the next update `v5.44.4.4`
> 
> - Reloaded tabs will now remain in their group (if set)
> - Reloaded tabs will **not** automatically refocus (they'll do their reloading in the background)
> - Reloaded tabs will stay at their current position (i.e. "3rd from left")

_Originally posted by @Ephellon in https://github.com/Ephellon/Twitch-Tools/issues/22#issuecomment-2292758565_
            
<hr>

- Remain in group and position confirm, looks good.

- Not auto refocus, has some problems: If the tab is not the last, and foreground. It will lose the foreground and activate the next tab.

I still don't understand why a new tab needs to be created to replace the existing one instead of refreshing the page. Creating a new tab will cause a lot of settings that are specific to the particular tab to fail, such as mute, discard, etc.

**Comment by Ephellon** [comment]
Tabs that hang will continue to hang unless a new tab is created. Any tab that fails to respond to the backend 3 consecutive times will be deemed "hung" and reloaded.

**Comment by Ephellon** [comment]
And I'll add some logic to force the currently active tab in a window to refocus after a reload

**Comment by Ephellon** [comment]
See #18

**Comment by Mishasama** [comment]
> Tabs that hang will continue to hang unless a new tab is created. Any tab that fails to respond to the backend 3 consecutive times will be deemed "hung" and reloaded.

How about trying to use discard and refresh instead?
For reference: [auto-tab-discard](https://github.com/rNeomy/auto-tab-discard/)

**Comment by Mishasama** [comment]
Then would it be possible to provide an option for turning off the reloading? I don't seem to have come across a situation so far where I need to do that.

Because it reloads all my tabs every time, but there's actually nothing wrong with many of them, it's not even a streaming page, I just have it on standby in the background. There were some that I even intentionally discarded to save on system resource usage, but it reloaded them as well.

**Comment by Ephellon** [comment]
Yes. I'll mock up a design later

**Comment by Ephellon** [comment]
@Mishasama Are you using the store (Chrome) or developer (GitHub) version of the extension?

**Comment by Ephellon** [comment]
See the README for instructions on installing the GitHub version. I'm about to push `v5.33.4.7-beta`

**Comment by Ephellon** [comment]
See [v5.33.4.7-beta](https://github.com/Ephellon/Twitch-Tools/releases/tag/5.33.4.7-beta)

**Comment by Mishasama** [comment]
> You can now disable automatic tab reloading

Seems has some bugs... I'm not sure relate or not for this. Still testing.
Will update when I confirm.

**Comment by Ephellon** [comment]
Any bugs to report?

**Comment by Mishasama** [comment]
> Any bugs to report?

Sorry, I turned off it since my CPU overheats when TTVT is on... This makes it especially hard for me to maintain the test for long periods.

Did you find the problem causing the high CPU usage?
Even if it's not on the settings page, the page with the extension turned on uses more CPU than without.

**Comment by Ephellon** [comment]
No, haven't found the sole issue yet but, I can get my CPU usage to +100% if I leave the Settings page open for more than a minute...

Will need to remove some things and test from there

**Comment by Ephellon** [comment]
Will move this to #27
