### ISSUE TITLE
Suggestion: Re-express "Lurk" button's intent

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#25]
**Describe the bug**

After test:
When it shows "Turn lurking off" the volume is normal.
When it shows "Turn lurking on" the volume is set low.
It confuses me.

**To Reproduce**

1. Reload the tab
2. Click on 'Lurking' button
3. Click it again
4. See the error?

**Expected behavior**

Should make it clear what state for now.
For example, "Lurking is ON" or "Lurking is OFF"

**Screenshots**

![image](https://github.com/user-attachments/assets/66120148-27d8-4884-beb1-2640a0cb941d)
![image](https://github.com/user-attachments/assets/cfcdacda-3fb5-445d-877c-ed4a48acde87)

**Extension Information**
 - Version: `5.33.4.6`
 - Source: `store` 
 - Browser: `edge`
 - Operating System: `Windows`

**Additional comments**

**Comment by Ephellon** [comment]
The text is clear... The provided example just flips the status text...

`Turn lurking off` &mdash; Release volume control (return to what the user had)
`Turn lurking on` &mdash; Take control of the volume (set it to the `Lurking Volume` setting)

![image](https://github.com/user-attachments/assets/880f1c33-dd3f-45f9-b001-59c527033186)

**Comment by Mishasama** [comment]
I mean...
`Turn lurking off` = Turned lurking off? Press the button to turn the lurking off?
The "Turn" is a verb. or a nom.?

I think ambiguity should be avoided as much as possible, right?

**Comment by Ephellon** [comment]
Yes, the message should be short and unambiguous. Just as Twitch has the *Follow* and *Unfollow* buttons.

----

*Turn lurking off* implies it is already enabled—pushing the button will turn it off.

- `Will turn` &hArr; `Turn` • future/present tense—will/is turn(ing)
- `Turned` • past tense—did turn

----

The best, alternative solution would be single-word replacements:

- `Lurk` or `Start Lurking`
- `Unlurk` or `Stop Lurking`

**Comment by Mishasama** [comment]
I prefer `Lurk` & `Unlurk`. Short & clear. And it's consistent with Twitch's phrasing conventions.
