### ISSUE TITLE
Issue: Subscribers-only page invoke subscription button and loop infinitely

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#28]
**Describe the bug**

When you didn't have sub someone, and try to watch VODs. TTVT will keep clicking on the sub button.

**To Reproduce**

1. Go to the sub-only page without subs
2. See error

**Expected behavior**

What are you doing? Okay, okay! I will subscribe. But first, stop clicking it over and over again to prevent me from subscribing, OK? 😅

**Screenshots**

**Extension Information**
 - Version: `5.33.4.7`
 - Source:  `GitHub`
 - Browser: `edge`
 - Operating System: `Windows`

**Additional comments**

I hope you don't mind me throwing in a bunch of issues to keep you busy all of a sudden.

**Comment by Ephellon** [comment]
I need an example page

**Comment by Mishasama** [comment]
[example page](https://www.twitch.tv/sinosinodai?tt-err-get=ch-tw-tracker%2Cch-tw&tt-err-vid=video-recovery--player-error%2Cvideo-recovery--player-error&tt-err-vid=video-recovery--player-error)

**Comment by Ephellon** [comment]
I am not getting any button clicking, it just moves onto the next stream. Do you have **First in Line** enabled?

**Comment by Ephellon** [comment]
- The extension is set to __ignore__ URLs matching `{username}/videos/\d*` → `https://www.twitch.tv/videos/2230843459`
- It also navigates away from the `{username}/videos/` page (intended)
    - Is this what you're talking about?

**Comment by Mishasama** [comment]
> I am not getting any button clicking, it just moves onto the next stream. Do you have **First in Line** enabled?

NO. I prefer to stay on the offline page and wait for them online as real `First in Line`.

> It also navigates away from the `{username}/videos/` page (intended)
> * Is this what you're talking about?

No, check this out.
![0408c341-e619-4f13-92de-0ed6fc7fe500](https://github.com/user-attachments/assets/c87cdbfd-84ba-4741-be28-77016e454fb5)

I did nothing in this video. I just moved the mouse to show you that I have no way to close the popup by clicking on the empty area.

Upload ID: `nuO6fi`
Try it yourself?

**Comment by Ephellon** [comment]
I see. That definitely does not happen on any of my machines. I'll change the language and see if that's the issue

**Comment by Ephellon** [comment]
😊 or not. Because Twitch has to do bot checks when changing your language.

**Comment by Mishasama** [comment]
Anything I can help you with?

**Comment by Ephellon** [comment]
Not at this very moment. I have to wait for Twitch to recognize me as human (Twitch Integrity Check)

**Comment by Ephellon** [comment]
It is a language issue!

**Comment by Ephellon** [comment]
`tools.js:15289`

```js
        let errorMessage = $('[data-a-target*="player"i]:is([data-a-target*="content"i], [data-a-target*="gate"i]) [data-a-target*="text"i]');

        // ...

        $error('The stream ran into an error:', errorMessage.textContent, new Date);

        // ↓↓↓ PROBLEMATIC LINE ↓↓↓ //
        if(/\b(subscribe|mature)\b/i.test(errorMessage.textContent)) {
            let next = await GetNextStreamer(STREAMER.name);

            // Subscriber only, etc.
            if(defined(next))
                goto(parseURL(next.href).addSearch({ tool: 'video-recovery--non-subscriber' }).href);
        } else {
            ($('button', errorMessage) ?? errorMessage.closest('button'))?.click();

            // Failed to play video at...
            addReport({ 'TTV-Tools-failed-to-recover-video': (errorMessage?.textContent ?? 'Unknown error') });

            RECOVERING_VIDEO = false;
        }
```

**Comment by Ephellon** [comment]
Temporary solution: turn off `Recover Video`

**Comment by Ephellon** [comment]
I will need to add translations of phrases that mean "mature" or "subscribe"

**Comment by Ephellon** [comment]
I think I have a solution?

The streamer's name can always be found at `a[href] h1`, and the "Please subscribe 😳" message always includes the streamer's name as well... If it's on top of the video, then count it?!

**Comment by Mishasama** [comment]
I'm guessing you've fallen into a logical error.
Is your current decision condition based on "a button appears in the player area, and if it does, click it"?

**Comment by Ephellon** [comment]
> I'm guessing you've fallen into a logical error. Is your current decision condition based on "a button appears in the player area, and if it does, click it"?

Sort of: if there's a button, check it's (English) contents for the words "subscribe" or "mature"; if the words are not found, click the button

This was used for clicking the "Error ###" button on streams, since they can vary

**Comment by Ephellon** [comment]
The new logic: if the channel's name in not in the button's ancestry, click it

```js
        let latin = top.location.pathname.slice(1).split('/').shift();
        let native = $(`a[href$="${ latin }"i] [class*="title"]`)?.textContent ?? latin;

        if(errorMessage.closest('[class*="content"i]:is([role], [data-a-target])')?.textContent?.includes(native)) {
            let next = await GetNextStreamer(latin);

            // Subscriber only, etc.
            if(defined(next))
                goto(parseURL(next.href).addSearch({ tool: 'video-recovery--non-subscriber' }).href);
        }
```

**Comment by Mishasama** [comment]
> Sort of: if there's a button, check its (English) contents for the words "subscribe" or "mature"; if the words are not found, click the button

That's right then, it would get into language adaptation issues.

In my opinion, you should make an advance decision based on whether the player gets the m3u8 address or not.
Since "no subscription" or "mature content" is pre-blocked, you can't get the m3u8 address at this state. Only when the m3u8 address is obtained, the button to reload the player may appear, and the above button will never appear.

**Comment by Ephellon** [comment]
Not really trying to deal with Chrome's MV3 implementation of network requests 😊 maybe in a future version, when I can get access to the Twitch API (and not be labeled a bot every week)

**Comment by Mishasama** [comment]
> be labeled a bot every week

Why is that? Is it just because of the frequent switching of the display language?

**Comment by Ephellon** [comment]
No. Twitch just won't fix their bot-detection. [It happens regularly](https://www.reddit.com/r/Twitch/comments/y8pwf6/i_cant_sign_into_my_account_i_get_an_error_every/)

**Comment by Mishasama** [comment]
> No. Twitch just won't fix their bot-detection. [It happens regularly](https://www.reddit.com/r/Twitch/comments/y8pwf6/i_cant_sign_into_my_account_i_get_an_error_every/)

That's weird, I'm logged in on 3 browsers. Including Firefox, Edge, and Chrome. and watch the live stream in multiple browsers simultaneously every day. None have had issues with not being able to log in or being logged out of their login status.

Could it be something to do with your IP or network connectivity?
Like a filter rule in DNS blocking a certain detection script or something.
(I've had similar login problems due to incomplete page content loading)

**Comment by Ephellon** [comment]
Twitch doesn't log out, it simply ignores several requests: language change, viewing some settings, collecting bonus channel points, purchasing channel point items, using/buying bits, using whispers, checking notifications, following channels, subscribing, viewing some ads, etc.

Also, yes, it is a known issue due to my IP address, but it's Twitch's poor implementation causing the problem... no other service gives me an issue

**Comment by Ephellon** [comment]
Hence, why some issues take forever to close 😊

**Comment by Mishasama** [comment]
> yes, it is a known issue due to my IP address

As a temporary solution, maybe try using the free Cloudflare Warp to bypass the IP issue?

**Comment by Ephellon** [comment]
Not a viable solution, it will relabel me as a bot in about an hour

**Comment by Mishasama** [comment]
> it will relabel me as a bot in about an hour

Problems with browser [fingerprinting](https://webextension.org/listing/canvas-fingerprint-blocker.html)?

**Comment by Ephellon** [comment]
That's for advertisements... I don't use fingerprinting

**Comment by Ephellon** [comment]
Fingerprinting is used by trackers to tell users apart: as in actual fingerprints

**Comment by Mishasama** [comment]
> Fingerprinting is used by trackers to tell users apart: as in actual fingerprints

Doesn't that explain why you've been repeatedly marked as a robot? Maybe your fingerprints have already been marked as a robot.

**Comment by Ephellon** [comment]
No. Integrity checks are on Twitch's servers...

**Comment by Mishasama** [comment]
Language Changes -> Log Fingerprint -> Match Fingerprints -> Block Requests

This is one of how the online services keeps banning the alt accounts.

**Comment by Ephellon** [comment]
I don't have any alt accounts

**Comment by Ephellon** [comment]
This is a Twitch-server issue. Not a user issue
