### ISSUE TITLE
Issue: Stream previews still coming up when disabled

### ISSUE THREAD

**Issue by lrmtheboss** [Ephellon/Twitch-Tools#32]
**Describe the bug**
Steam Previews still pop up even though I have them disabled in the settings.

**To Reproduce**
1. Have stream previews disabled in the extension's settings.
2. Go to twitch
3. Hover over any steam and then the preview will pop up

**Expected behavior**
Stream previews don't pop up when hovering over a stream on the main page of Twitch

**Screenshots**

**Extension Information**
 - Version: `5.33.4.9`
 - Source: `Chrome Web Store`
 - Browser: `chrome`
 - Operating System: `Windows` & `Linux (Ubuntu)`

**Additional comments**
To confirm that it is caused by this extension, I disabled it using Extensity, and the problem when away.
I also tried various combinations of enabled extensions. As long as this one is enabled the issue persists.

**Comment by Ephellon** [comment]
*They display on the homepage even with the option disabled.*

```javascript
live_previews_on_hompage: if(top.location.pathname == '/') {
    •
    •
    •
}
```

**Comment by lrmtheboss** [comment]
Could an option be added to stop them from displaying on the homepage?

**Comment by Ephellon** [comment]
Changed in upcoming version:

```javascript
live_previews_on_hompage: if(top.location.pathname == '/')
    when(() => parseBool(Settings?.stream_preview), 3e3).then(() => {
        •
        •
        •
    });
```

**Comment by Ephellon** [comment]
@lrmtheboss The `Stream Preview` setting will be used in the upcoming change.
